export function parseDefensiveJson(result: string): any {
  if (!result || typeof result !== "string") {
    throw new Error("Empty or invalid string provided for JSON parsing");
  }

  try {
    // Attempt direct parse first in case it's clean
    return JSON.parse(result.trim());
  } catch (e) {
    // If it fails, try stripping markdown blocks and <think> blocks
    try {
      // Remove <think>...</think> blocks generated by reasoning models
      let preprocessed = result.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();

      const jsonMatch = preprocessed.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
      const cleanStr = jsonMatch ? jsonMatch[1].trim() : preprocessed.trim();
      // Remove trailing text after the last brace or bracket if the LLM hallucinated
      const firstBrace = cleanStr.indexOf('{');
      const firstBracket = cleanStr.indexOf('[');
      
      let startIdx = 0;
      if (firstBrace !== -1 && firstBracket !== -1) {
        startIdx = Math.min(firstBrace, firstBracket);
      } else if (firstBrace !== -1) {
        startIdx = firstBrace;
      } else if (firstBracket !== -1) {
        startIdx = firstBracket;
      }

      const lastBrace = cleanStr.lastIndexOf('}');
      const lastBracket = cleanStr.lastIndexOf(']');
      
      let endIdx = cleanStr.length;
      if (lastBrace !== -1 && lastBracket !== -1) {
        endIdx = Math.max(lastBrace, lastBracket) + 1;
      } else if (lastBrace !== -1) {
        endIdx = lastBrace + 1;
      } else if (lastBracket !== -1) {
        endIdx = lastBracket + 1;
      }

      const sliced = cleanStr.slice(startIdx, endIdx);
      return JSON.parse(sliced);
    } catch (innerError) {
      console.error("Failed to parse AI JSON response after sanitization:", result);
      throw new Error("AI response was not valid JSON");
    }
  }
}
